In [17]:
#Libary 
import pandas as pd 
import numpy as np
import sklearn as sk

In [18]:
#Load the dataset 
# data in csv file so we loaded the data set using the pandas

df = pd.read_csv(
    r"C:\Users\surya\OneDrive\Desktop\ML\DATA\House_Rent_Dataset.csv"
)

In [19]:
df

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2022-05-18,2,15000,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4742,2022-05-15,3,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
4743,2022-07-10,3,35000,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
4744,2022-07-06,3,45000,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent
4745,2022-05-04,2,15000,1000,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

In [20]:
#informations about the data
print("It is the head of the csv file :-")
print(df.head)
print("\n \n")
print("="*80)
print("It is the infromations of the csv file :-")
print(df.info())
print("="*80)
print("It is the sum  of the csv file :-")
print(df.isnull().sum().sum())

It is the head of the csv file :-
<bound method NDFrame.head of        Posted On  BHK   Rent  Size            Floor    Area Type  \
0     2022-05-18    2  10000  1100  Ground out of 2   Super Area
1     2022-05-13    2  20000   800       1 out of 3   Super Area
2     2022-05-16    2  17000  1000       1 out of 3   Super Area
3     2022-07-04    2  10000   800       1 out of 2   Super Area
4     2022-05-09    2   7500   850       1 out of 2  Carpet Area
...          ...  ...    ...   ...              ...          ...
4741  2022-05-18    2  15000  1000       3 out of 5  Carpet Area
4742  2022-05-15    3  29000  2000       1 out of 4   Super Area
4743  2022-07-10    3  35000  1750       3 out of 5  Carpet Area
4744  2022-07-06    3  45000  1500     23 out of 34  Carpet Area
4745  2022-05-04    2  15000  1000       4 out of 5  Carpet Area

                 Area Locality       City Furnishing Status  Tenant Preferred  \
0                       Bandel    Kolkata       Unfurnished  Bachelors/Family
1     Phool Bagan, Kankurgachi    Kolkata    Semi-Furnished  Bachelors/Family
2      Salt Lake City Sector 2    Kolkata    Semi-Furnished  Bachelors/Family
3                  Dumdum Park    Kolkata       Unfurnished  Bachelors/Family
4                South Dum Dum    Kolkata       Unfurnished         Bachelors
...                        ...        ...               ...               ...
4741              Bandam Kommu  Hyderabad    Semi-Furnished  Bachelors/Family
4742      Manikonda, Hyderabad  Hyderabad    Semi-Furnished  Bachelors/Family
4743      Himayath Nagar, NH 7  Hyderabad    Semi-Furnished  Bachelors/Family
4744                Gachibowli  Hyderabad    Semi-Furnished            Family
4745           Suchitra Circle  Hyderabad       Unfurnished         Bachelors

      Bathroom Point of Contact
0            2    Contact Owner
1            1    Contact Owner
2            1    Contact Owner
3            1    Contact Owner
4            1    Contact Owner
...        ...              ...
4741         2    Contact Owner
4742         3    Contact Owner
4743         3    Contact Agent
4744         2    Contact Agent
4745         2    Contact Owner

[4746 rows x 12 columns]>



================================================================================
It is the infromations of the csv file :-
<class 'pandas.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Posted On          4746 non-null   str
 1   BHK                4746 non-null   int64
 2   Rent               4746 non-null   int64
 3   Size               4746 non-null   int64
 4   Floor              4746 non-null   str
 5   Area Type          4746 non-null   str
 6   Area Locality      4746 non-null   str
 7   City               4746 non-null   str
 8   Furnishing Status  4746 non-null   str
 9   Tenant Preferred   4746 non-null   str
 10  Bathroom           4746 non-null   int64
 11  Point of Contact   4746 non-null   str
dtypes: int64(4), str(8)
memory usage: 887.8 KB
None
================================================================================
It is the sum  of the csv file :-
0

In [21]:
#In csv file unnessary column is delect 
df = df.drop(columns=["Point of Contact"])
print("After delect the Point of Contact column")
df.head(3)

After delect the Point of Contact column

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1

In [22]:
#It show the duplicated value in dataset 
df.index.duplicated().sum()

np.int64(0)

In [24]:
#it show the shape of the dataset
df.shape

(4746, 11)

In [ ]:
#Doup all the